per_listener_settings false
allow_anonymous false
allow_zero_length_clientid false
password_file /run/mosquitto/passwords
acl_file /run/mosquitto/acl

listener 1883 0.0.0.0
protocol mqtt

persistence true
persistence_location /mosquitto/data/
autosave_interval 60

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
