per_listener_settings true
allow_zero_length_clientid false

listener 1883 0.0.0.0
protocol mqtt
allow_anonymous false
password_file /run/mosquitto/passwords
acl_file /run/mosquitto/acl

persistence true
persistence_location /mosquitto/data/
autosave_interval 60

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
