export * from "./enfermedades";
export * from "./fenologia-termica";
export * from "./agrometeorologia";
export * from "./frio-termico";
export * from "./clasificacion-termica-cultivos";
export * from "./fenologia-registros";
export * from "./catalogo-termico-varietal";
export * from "./ficha-varietal";
export * from "./catalogo-cultivos";
