import { IZonaGeografica } from 'modelos/src';

export const PROVINCIAS_ARGENTINA_BASE: IZonaGeografica[] = [
  {
    id: 'ar-buenos-aires',
    tipo: 'provincia',
    label: 'Buenos Aires',
    provincia: 'Buenos Aires',
    coordenadas: { lat: -36.6769, lng: -60.5588 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-caba',
    tipo: 'provincia',
    label: 'Ciudad Autonoma de Buenos Aires',
    provincia: 'Ciudad Autonoma de Buenos Aires',
    coordenadas: { lat: -34.6037, lng: -58.3816 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-catamarca',
    tipo: 'provincia',
    label: 'Catamarca',
    provincia: 'Catamarca',
    coordenadas: { lat: -28.4696, lng: -65.7852 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-chaco',
    tipo: 'provincia',
    label: 'Chaco',
    provincia: 'Chaco',
    coordenadas: { lat: -26.3864, lng: -60.7658 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-chubut',
    tipo: 'provincia',
    label: 'Chubut',
    provincia: 'Chubut',
    coordenadas: { lat: -43.7886, lng: -68.5267 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-cordoba',
    tipo: 'provincia',
    label: 'Cordoba',
    provincia: 'Cordoba',
    coordenadas: { lat: -31.4167, lng: -64.1833 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-corrientes',
    tipo: 'provincia',
    label: 'Corrientes',
    provincia: 'Corrientes',
    coordenadas: { lat: -28.7743, lng: -57.8012 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-entre-rios',
    tipo: 'provincia',
    label: 'Entre Rios',
    provincia: 'Entre Rios',
    coordenadas: { lat: -32.0589, lng: -59.2014 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-formosa',
    tipo: 'provincia',
    label: 'Formosa',
    provincia: 'Formosa',
    coordenadas: { lat: -24.8958, lng: -59.9328 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-jujuy',
    tipo: 'provincia',
    label: 'Jujuy',
    provincia: 'Jujuy',
    coordenadas: { lat: -23.3201, lng: -65.7643 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-la-pampa',
    tipo: 'provincia',
    label: 'La Pampa',
    provincia: 'La Pampa',
    coordenadas: { lat: -36.6167, lng: -64.2833 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-la-rioja',
    tipo: 'provincia',
    label: 'La Rioja',
    provincia: 'La Rioja',
    coordenadas: { lat: -29.4131, lng: -66.8558 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-mendoza',
    tipo: 'provincia',
    label: 'Mendoza',
    provincia: 'Mendoza',
    coordenadas: { lat: -32.8895, lng: -68.8458 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-misiones',
    tipo: 'provincia',
    label: 'Misiones',
    provincia: 'Misiones',
    coordenadas: { lat: -27.4269, lng: -55.9467 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-neuquen',
    tipo: 'provincia',
    label: 'Neuquen',
    provincia: 'Neuquen',
    coordenadas: { lat: -38.9516, lng: -68.0591 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-rio-negro',
    tipo: 'provincia',
    label: 'Rio Negro',
    provincia: 'Rio Negro',
    coordenadas: { lat: -40.8135, lng: -63.0003 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-salta',
    tipo: 'provincia',
    label: 'Salta',
    provincia: 'Salta',
    coordenadas: { lat: -24.7821, lng: -65.4232 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-san-juan',
    tipo: 'provincia',
    label: 'San Juan',
    provincia: 'San Juan',
    coordenadas: { lat: -31.5375, lng: -68.5364 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-san-luis',
    tipo: 'provincia',
    label: 'San Luis',
    provincia: 'San Luis',
    coordenadas: { lat: -33.295, lng: -66.3356 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-santa-cruz',
    tipo: 'provincia',
    label: 'Santa Cruz',
    provincia: 'Santa Cruz',
    coordenadas: { lat: -48.8155, lng: -69.9558 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-santa-fe',
    tipo: 'provincia',
    label: 'Santa Fe',
    provincia: 'Santa Fe',
    coordenadas: { lat: -31.5855, lng: -60.7238 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-santiago-del-estero',
    tipo: 'provincia',
    label: 'Santiago del Estero',
    provincia: 'Santiago del Estero',
    coordenadas: { lat: -27.7834, lng: -64.2642 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-tierra-del-fuego',
    tipo: 'provincia',
    label: 'Tierra del Fuego',
    provincia: 'Tierra del Fuego',
    coordenadas: { lat: -54.8019, lng: -68.303 },
    fuente: 'Chaman',
  },
  {
    id: 'ar-tucuman',
    tipo: 'provincia',
    label: 'Tucuman',
    provincia: 'Tucuman',
    coordenadas: { lat: -26.8083, lng: -65.2176 },
    fuente: 'Chaman',
  },
];
